name: Add changeset to Dependabot updates

on:
  pull_request_target:
    types: [opened, synchronize, labeled]

jobs:
  dependabot:
    name: Update Dependabot PR
    runs-on: ubuntu-latest
    if: contains(github.event.pull_request.labels.*.name, 'dependencies')

    permissions:
      contents: write

    steps:
      - name: Update PR
        uses: mscharley/dependency-changesets-action@v1.2.4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          use-conventional-commits: true
